# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broker_svc.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protobuf_msgs_pb2 as protobuf__msgs__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x10\x62roker_svc.proto\x12\x10kubefox.proto.v1\x1a\x13protobuf_msgs.proto2R\n\x06\x42roker\x12H\n\tSubscribe\x12\x17.kubefox.proto.v1.Event\x1a\x1e.kubefox.proto.v1.MatchedEvent(\x01\x30\x01\x42 Z\x1egithub.com/xigxog/kubefox/grpcb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "broker_svc_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\036github.com/xigxog/kubefox/grpc"
    _globals["_BROKER"]._serialized_start = 59
    _globals["_BROKER"]._serialized_end = 141
# @@protoc_insertion_point(module_scope)
